/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProcurementSystem;

import CustomResource.koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class in_out_material extends javax.swing.JFrame {

    Statement stm;
    ResultSet rs;
    Connection koneksi;
    String item;
    String item_name;
    String item_name_dis;
    String spec;
    String spec1;
    
    
    /**
     * Creates new form in_out_material
     */
    public in_out_material() {
        initComponents();
        MyWindow1();
        openDB();
        tampil();
    }
    
    
    
     private void openDB() {
        try {
            koneksi kon = new koneksi();
            koneksi = kon.getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "maaf, Tidak terhubung database");
        }
    }
     
     
     void tampil() {

        try {
            cb_material.removeAllItems();
            ResultSet myRess = koneksi.createStatement().executeQuery("select*from po_material");
            while (myRess.next()) {
                cb_material.addItem(myRess.getString("id_material_code") + "-" + myRess.getString("name_material"));
            }
        } catch (SQLException ex) {
        }

    }
     
      void combobox_material() {

        item = cb_material.getSelectedItem().toString();
        String[] parts = item.split("-");
        String id = parts[0];
        String id1 = parts[1];
        item = id;
        item_name = id1;

    }

      void tampil_comboboxdiscipline() {
        try {
            cb_discipline.removeAllItems();
            ResultSet myRess = koneksi.createStatement().executeQuery("select*from po_material_discipline where id_material_code = '" + item + "'");
            while (myRess.next()) {
                cb_discipline.addItem(myRess.getString("id_material_code") + "-" + myRess.getString("id_discipline_code") + "-" + myRess.getString("name_discipline"));
            }
        } catch (SQLException ex) {
        }

    }
      
      private void MyWindow1(){
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        
        
        int x = (screen.width/2) - (this.getSize().width/2);
        int y = (screen.height/2) - (this.getSize().height/2);
        this.setLocation(x,y);
    }
    
   void tampil_table_spek() {
        DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();
        int rowCount1 = model1.getRowCount();

        for (int i = rowCount1 - 1; i >= 0; i--) {
            model1.removeRow(i);
        }

        DefaultTableModel dataModel3 = (DefaultTableModel) jTable3.getModel();
        try {
            stm = koneksi.createStatement();
            rs = stm.executeQuery("SELECT * FROM po_material_spek where id_discipline_code = '" + spec + "'");
            while (rs.next()) {
                String[] data = {
                    rs.getString("id_material_spek"),
                    rs.getString("name_spek"),
                    rs.getString("stok")};
                dataModel3.insertRow(0, data);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "data gagal tampil");
        }

    }
   
    void combobox_spek() {
        spec = cb_discipline.getSelectedItem().toString();
        String[] parts = spec.split("-");
        String id = parts[0];
        String id1 = parts[1];
        String id2 = parts[2];
        spec = id + id1;
        spec1 = id1;
       item_name_dis = id2;

    }
      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        cb_material = new CustomResource.ComboBoxSuggestion();
        cb_discipline = new CustomResource.ComboBoxSuggestion();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        t_material_name = new CustomResource.CustomTextfield();
        t_date = new CustomResource.CustomTextfield();
        cb_in_out = new CustomResource.ComboBoxSuggestion();
        jScrollPane25 = new javax.swing.JScrollPane();
        t_remark = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        t_id_material = new CustomResource.CustomTextfield();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        t_c_stok = new CustomResource.CustomTextfield();
        t_amount = new CustomResource.CustomTextfield();
        jButton3 = new javax.swing.JButton();

        dateChooser1.setDateFormat("yyyy-MM-dd");
        dateChooser1.setTextRefernce(t_date);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_material.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Material" }));
        cb_material.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_material.setName(""); // NOI18N
        cb_material.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cb_materialPopupMenuWillBecomeVisible(evt);
            }
        });
        cb_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_materialActionPerformed(evt);
            }
        });
        jPanel1.add(cb_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 272, -1));

        cb_discipline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID #1", "MT", "VD", "EQ", "TR", "TO", "CO", "OE", "OS", "OC", "AI", "QI", "SC", "CS", "OI" }));
        cb_discipline.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_discipline.setName(""); // NOI18N
        cb_discipline.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cb_disciplinePopupMenuWillBecomeVisible(evt);
            }
        });
        cb_discipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_disciplineActionPerformed(evt);
            }
        });
        jPanel1.add(cb_discipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 272, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Spec", "Name Spec", "Stok"
            }
        ));
        jScrollPane1.setViewportView(jTable3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 515, 164));

        t_material_name.setLabelText("Material Name");
        t_material_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_material_nameActionPerformed(evt);
            }
        });
        jPanel1.add(t_material_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 220, -1));

        t_date.setLabelText("Date");
        jPanel1.add(t_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 240, -1));

        cb_in_out.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose In/Out", "In", "Out" }));
        cb_in_out.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_in_out.setName(""); // NOI18N
        cb_in_out.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cb_in_outPopupMenuWillBecomeVisible(evt);
            }
        });
        cb_in_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_in_outActionPerformed(evt);
            }
        });
        jPanel1.add(cb_in_out, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 148, -1));

        t_remark.setColumns(20);
        t_remark.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        t_remark.setRows(5);
        t_remark.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                t_remarkMouseWheelMoved(evt);
            }
        });
        jScrollPane25.setViewportView(t_remark);

        jPanel1.add(jScrollPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 210, -1));

        jLabel1.setText("Remark");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, -1, -1));

        t_id_material.setLabelText("ID Material");
        t_id_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_id_materialActionPerformed(evt);
            }
        });
        jPanel1.add(t_id_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 240, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Choose Material");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 530, 20));

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Set In/Out Material");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 530, 20));

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, -1, -1));

        t_c_stok.setLabelText("Current Stock");
        t_c_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_c_stokActionPerformed(evt);
            }
        });
        jPanel1.add(t_c_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 120, -1));

        t_amount.setLabelText("Amount");
        t_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_amountActionPerformed(evt);
            }
        });
        jPanel1.add(t_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 240, -1));

        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_materialPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_materialPopupMenuWillBecomeVisible
               // TODO add your handling code here:
    }//GEN-LAST:event_cb_materialPopupMenuWillBecomeVisible

    private void cb_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_materialActionPerformed
if (cb_material.getSelectedItem() == null) {

        } else {
            combobox_material();

            tampil_comboboxdiscipline();
            
        }     // TODO add your handling code here:
    }//GEN-LAST:event_cb_materialActionPerformed

    private void cb_disciplinePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_disciplinePopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_disciplinePopupMenuWillBecomeVisible

    private void cb_disciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_disciplineActionPerformed
if (cb_discipline.getSelectedItem() == null) {

        } else {
          combobox_spek();
tampil_table_spek();
            
        } 
       // TODO add your handling code here:
    }//GEN-LAST:event_cb_disciplineActionPerformed

    private void cb_in_outPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_in_outPopupMenuWillBecomeVisible
     cb_in_out.removeItem("Choose In/Out");   
    }//GEN-LAST:event_cb_in_outPopupMenuWillBecomeVisible

    private void cb_in_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_in_outActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_in_outActionPerformed

    private void t_remarkMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_t_remarkMouseWheelMoved

    }//GEN-LAST:event_t_remarkMouseWheelMoved

    private void t_material_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_material_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_material_nameActionPerformed

    private void t_id_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_id_materialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_id_materialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String id;
String id1;
DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();
int row = jTable3.getSelectedRow();
id = item +"-"+spec1+"-"+model1.getValueAt(row, 0);
id1 = item_name +"-"+item_name_dis+"-"+model1.getValueAt(row, 1);
t_material_name.setText(id1);
t_id_material.setText(id);
t_c_stok.setText((String) model1.getValueAt(row, 2));


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_c_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_c_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_c_stokActionPerformed

    private void t_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_amountActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();
        String[] parts = t_id_material.getText().split("-");
        String id2 = parts[2];
        int jumlah = 0;
        try {
            stm = koneksi.createStatement();
            String sql = "insert into wr_in_out (id_spec,in_out,amount,date,remark,id_material,name_material) values('" + id2 + "'"
                    + ",'" + cb_in_out.getSelectedItem().toString() + "'"
                    + ",'" +t_amount.getText() + "'"
                    + ",'" + t_date.getText() + "'"
                    + ",'" + t_remark.getText() + "'"
                    + ",'" + t_id_material.getText() + "'"
                    + ",'" + t_material_name.getText() + "')";
            stm.executeUpdate(sql);
            stm.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error" + e, "GAGAL", JOptionPane.WARNING_MESSAGE);
        }
        
        if (cb_in_out.getSelectedItem().equals("In")){
        int a = Integer.parseInt(t_c_stok.getText());
        int b = Integer.parseInt(t_amount.getText());
        jumlah = a + b;
        
        } else if (cb_in_out.getSelectedItem().equals("Out")){
        int a = Integer.parseInt(t_c_stok.getText());
        int b = Integer.parseInt(t_amount.getText());
        jumlah = a - b;
        }
         System.out.println(jumlah);
         try {
            stm = koneksi.createStatement();
            String sql = "UPDATE po_material_spek SET stok = '"+jumlah+"' WHERE id_material_spek = '"+id2+"'";
            stm.executeUpdate(sql);
            stm.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error" + e, "GAGAL", JOptionPane.WARNING_MESSAGE);
        }

        JOptionPane.showMessageDialog(null, "Submit Successfully");
        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(in_out_material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(in_out_material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(in_out_material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(in_out_material.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new in_out_material().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomResource.ComboBoxSuggestion cb_discipline;
    private CustomResource.ComboBoxSuggestion cb_in_out;
    private CustomResource.ComboBoxSuggestion cb_material;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JTable jTable3;
    private CustomResource.CustomTextfield t_amount;
    private CustomResource.CustomTextfield t_c_stok;
    private CustomResource.CustomTextfield t_date;
    private CustomResource.CustomTextfield t_id_material;
    private CustomResource.CustomTextfield t_material_name;
    private javax.swing.JTextArea t_remark;
    // End of variables declaration//GEN-END:variables
}
