/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ProcurementSystem;

import CustomResource.koneksi;
import HumanResource.Employe_list;
import Main.MasterForm;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class po_rfq extends MasterForm {

    Statement stm;
    ResultSet rs;
    Connection koneksi;
    int id_po;
    int a = 1;
    int b = 1;
    String id;

    /**
     * Creates new form po
     */
    public po_rfq() {
        initComponents();
        openDB();
        addtext();
        id_employee();
        tampil_table();

    }

    private void openDB() {
        try {
            koneksi kon = new koneksi();
            koneksi = kon.getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "maaf, Tidak terhubung database");
        }
    }

    private void id_employee() {
        String sql = "select max(id) from po_rfq";
        try {
            stm = koneksi.createStatement();
            rs = stm.executeQuery(sql);
            while (rs.next()) {
                int a = rs.getInt(1);
                id_po = a + 1;

            }
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }
        id = Integer.toString(id_po);
        t_id_po.setText("RFQ-" + id);

    }

    private void addtext() {

        try {
            stm = koneksi.createStatement();
            rs = stm.executeQuery("select * from biz_partner where biz_id = " + CustomResource.EmployeeSession.getbiz_id() + "");

            while (rs.next()) {
                String a = rs.getString("address") + " " + "RT" + "/" + rs.getString("rt") + "RW" + "/" + rs.getString("rw") + " " + rs.getString("city") + " " + rs.getString("province") + " " + rs.getString("postcode");
                t_name.setText(rs.getString("name"));
                t_hp.setText(rs.getString("no_hp"));
                t_emial.setText(rs.getString("email"));
                t_addres.setText(a);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    void tampil_table() {

        DefaultTableModel dataModel2 = (DefaultTableModel) jTable1.getModel();
        int rowCount1 = dataModel2.getRowCount();

        for (int i = rowCount1 - 1; i >= 0; i--) {
            dataModel2.removeRow(i);
        }

        try {
            stm = koneksi.createStatement();
            rs = stm.executeQuery("select*from po_material_request where status = '1'");
            while (rs.next()) {

                String[] data = {
                    "MR-" + rs.getString("id_material_request"),
                    rs.getString("id_material_code"),
                    rs.getString("material") + "-"
                    + rs.getString("discipline") + "-"
                    + rs.getString("spec"),
                    rs.getString("tanggal_request"),
                    rs.getString("stok"),
                    rs.getString("qty"),
                    rs.getString("remark")};
                dataModel2.insertRow(0, data);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "data gagal ta mpil");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser2 = new com.raven.datechooser.DateChooser();
        dateChooser3 = new com.raven.datechooser.DateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        t_id_po = new CustomResource.CustomTextfield();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        t_name = new CustomResource.CustomTextfield();
        t_hp = new CustomResource.CustomTextfield();
        t_emial = new CustomResource.CustomTextfield();
        t_stock_needs = new CustomResource.CustomTextfield();
        t_addres = new CustomResource.CustomTextfield();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        t_tgl_rfq = new CustomResource.CustomTextfield();
        t_mr_id = new CustomResource.CustomTextfield();
        t_material_id = new CustomResource.CustomTextfield();
        t_material_name = new CustomResource.CustomTextfield();
        t_stock_needs1 = new CustomResource.CustomTextfield();
        t_stock_needs2 = new CustomResource.CustomTextfield();
        t_tgl_rfq1 = new CustomResource.CustomTextfield();

        dateChooser2.setDateFormat("yyyy-MM-dd");
        dateChooser2.setTextRefernce(t_tgl_rfq);

        dateChooser3.setDateFormat("yyyy-MM-dd");
        dateChooser3.setTextRefernce(t_tgl_rfq);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_id_po.setEnabled(false);
        t_id_po.setLabelText("ID PO");
        jPanel1.add(t_id_po, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 150, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MR ID", "ID Material", "Material Name", "Date Request", "Stock Needs", "Qty", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 660, 140));

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LIST MATERIAL REQUEST");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 650, 20));

        jButton6.setText("Search Supplier");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 130, -1));

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REQUEST FOR QUATATION");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 650, 20));

        t_name.setEnabled(false);
        t_name.setLabelText("Supplier");
        jPanel1.add(t_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 257, -1));

        t_hp.setEnabled(false);
        t_hp.setLabelText("Mobile No");
        jPanel1.add(t_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 257, -1));

        t_emial.setEnabled(false);
        t_emial.setLabelText("E-mail");
        jPanel1.add(t_emial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 257, -1));

        t_stock_needs.setLabelText("Stocks Requirement");
        t_stock_needs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_stock_needsKeyTyped(evt);
            }
        });
        jPanel1.add(t_stock_needs, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 610, 257, -1));

        t_addres.setEnabled(false);
        t_addres.setLabelText("Address");
        jPanel1.add(t_addres, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 257, -1));

        jButton7.setText("SUBMIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 850, 102, -1));

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("RFQ ITEMS SELECTED");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 660, 20));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RFQ ID", "MR ID", "Material Name", "Stock Needs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 700, 660, 140));

        jButton8.setText("ADD");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, 102, -1));

        t_tgl_rfq.setLabelText("RFQ Date");
        jPanel1.add(t_tgl_rfq, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 257, -1));

        t_mr_id.setEditable(false);
        t_mr_id.setLabelText("MR ID");
        jPanel1.add(t_mr_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 257, -1));

        t_material_id.setEditable(false);
        t_material_id.setLabelText("Material ID");
        jPanel1.add(t_material_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 600, 257, -1));

        t_material_name.setEditable(false);
        t_material_name.setLabelText("Material Name");
        jPanel1.add(t_material_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 257, -1));

        t_stock_needs1.setLabelText("Payment Condition");
        t_stock_needs1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_stock_needs1KeyTyped(evt);
            }
        });
        jPanel1.add(t_stock_needs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 257, -1));

        t_stock_needs2.setLabelText("Estimate Date Delivery");
        t_stock_needs2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_stock_needs2KeyTyped(evt);
            }
        });
        jPanel1.add(t_stock_needs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 257, -1));

        t_tgl_rfq1.setLabelText("RFQ Close Date");
        jPanel1.add(t_tgl_rfq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 257, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1097, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (t_name.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Supplier Cannot Be Empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (jTable2.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Table Materials Cannot Be Empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            try {
                stm = koneksi.createStatement();
                String sql = "insert into po_rfq (biz_id,rfq_date) values('" + CustomResource.EmployeeSession.getbiz_id() + "'"
                        + ",'" + t_tgl_rfq.getText() + "')";
                stm.executeUpdate(sql);
                stm.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "error" + e, "GAGAL", JOptionPane.WARNING_MESSAGE);
            }

            int jtabelrows = jTable2.getRowCount();

            for (int i = 0; i <= jtabelrows - 1; i++) {
                DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();

                String mr_id = (String) model1.getValueAt(i, 0);
                String mr_id1 = (String) model1.getValueAt(i, 1);
                String mr_id2 = (String) model1.getValueAt(i, 2);
                String mr_id3 = (String) model1.getValueAt(i, 3);

                String[] parts = mr_id.split("-");
                String id = parts[1];
                String[] parts1 = mr_id1.split("-");
                String id1 = parts1[1];

                try {
                    stm = koneksi.createStatement();
                    String sql = "insert into po_rfq_items (rfq_id,mr_id,material_name,stock_needs) values('" + id + "'"
                            + ",'" + id1 + "'"
                            + ",'" + mr_id2 + "'"
                            + ",'" + mr_id3 + "')";
                    stm.executeUpdate(sql);
                    stm.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "error" + e, "GAGAL", JOptionPane.WARNING_MESSAGE);
                }

            }

            JOptionPane.showMessageDialog(null, "Data Saved");

            DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();
            for (int i = jtabelrows - 1; i >= 0; i--) {
                model1.removeRow(i);
            }

        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        CustomResource.EmployeeSession.setsesiform("3");
        new Employe_list().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (t_name.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Supplier Cannot Be Empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (t_mr_id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Materials Cannot Be Empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            int c = 0;

            DefaultTableModel dataModel2 = (DefaultTableModel) jTable2.getModel();
            int rowCount1 = dataModel2.getRowCount();
            for (int i = rowCount1 - 1; i >= 0; i--) {
                if (dataModel2.getValueAt(i, 1).equals(t_mr_id.getText())) {
                    JOptionPane.showMessageDialog(null, ""+t_mr_id.getText()+" Already Exists!!", "Warning", JOptionPane.WARNING_MESSAGE);
                    c = 1;
                }

            }

            if (c != 1) {
                String[] data = {
                    t_id_po.getText(),
                    t_mr_id.getText(),
                    t_material_name.getText(),
                    t_stock_needs.getText()};
                dataModel2.insertRow(0, data);
            }

        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();

        t_mr_id.setText((String) model1.getValueAt(row, 0));
        t_material_name.setText((String) model1.getValueAt(row, 2));
        t_material_id.setText((String) model1.getValueAt(row, 1));
        t_stock_needs.setText((String) model1.getValueAt(row, 4));

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void t_stock_needsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_stock_needsKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
        if (t_stock_needs.getText().length() > 15) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_t_stock_needsKeyTyped

    private void t_stock_needs1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_stock_needs1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_stock_needs1KeyTyped

    private void t_stock_needs2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_stock_needs2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_stock_needs2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.datechooser.DateChooser dateChooser2;
    private com.raven.datechooser.DateChooser dateChooser3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private CustomResource.CustomTextfield t_addres;
    private CustomResource.CustomTextfield t_emial;
    private CustomResource.CustomTextfield t_hp;
    private CustomResource.CustomTextfield t_id_po;
    private CustomResource.CustomTextfield t_material_id;
    private CustomResource.CustomTextfield t_material_name;
    private CustomResource.CustomTextfield t_mr_id;
    private CustomResource.CustomTextfield t_name;
    private CustomResource.CustomTextfield t_stock_needs;
    private CustomResource.CustomTextfield t_stock_needs1;
    private CustomResource.CustomTextfield t_stock_needs2;
    private CustomResource.CustomTextfield t_tgl_rfq;
    private CustomResource.CustomTextfield t_tgl_rfq1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void formrefresh() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
