/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProcurementSystem;

import CustomResource.koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Supplier_disc extends javax.swing.JFrame {

    Statement stm;
    ResultSet rs;
    Connection koneksi;
    String item;
    String item_name;
    String item_name_dis;
    String spec;
    String spec1;
    
    
    /**
     * Creates new form in_out_material
     */
    public Supplier_disc() {
        initComponents();
        MyWindow1();
        openDB();
        tampil();
    }
    
    
    
     private void openDB() {
        try {
            koneksi kon = new koneksi();
            koneksi = kon.getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "maaf, Tidak terhubung database");
        }
    }
     
     
     void tampil() {

        try {
            cb_material.removeAllItems();
            ResultSet myRess = koneksi.createStatement().executeQuery("select*from po_material");
            while (myRess.next()) {
                cb_material.addItem(myRess.getString("id_material_code") + "-" + myRess.getString("name_material"));
            }
        } catch (SQLException ex) {
        }

    }
     
      void combobox_material() {

        item = cb_material.getSelectedItem().toString();
        String[] parts = item.split("-");
        String id = parts[0];
        String id1 = parts[1];
        item = id;
        item_name = id1;

    }

      void tampil_comboboxdiscipline() {
        try {
            cb_discipline.removeAllItems();
            ResultSet myRess = koneksi.createStatement().executeQuery("select*from po_material_discipline where id_material_code = '" + item + "'");
            while (myRess.next()) {
                cb_discipline.addItem(myRess.getString("id_material_code") + "-" + myRess.getString("id_discipline_code") + "-" + myRess.getString("name_discipline"));
            }
        } catch (SQLException ex) {
        }

    }
      
      private void MyWindow1(){
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        
        
        int x = (screen.width/2) - (this.getSize().width/2);
        int y = (screen.height/2) - (this.getSize().height/2);
        this.setLocation(x,y);
    }
    
   void tampil_table_spek() {
        DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();
        int rowCount1 = model1.getRowCount();

        for (int i = rowCount1 - 1; i >= 0; i--) {
            model1.removeRow(i);
        }

        DefaultTableModel dataModel3 = (DefaultTableModel) jTable3.getModel();
        try {
            stm = koneksi.createStatement();
            rs = stm.executeQuery("SELECT * FROM po_material_spek where id_discipline_code = '" + spec + "'");
            while (rs.next()) {
                String[] data = {
                    rs.getString("id_material_spek"),
                    rs.getString("name_spek"),
                    rs.getString("stok")};
                dataModel3.insertRow(0, data);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "data gagal tampil");
        }

    }
   
    void combobox_spek() {
        spec = cb_discipline.getSelectedItem().toString();
        String[] parts = spec.split("-");
        String id = parts[0];
        String id1 = parts[1];
        String id2 = parts[2];
        spec = id + id1;
        spec1 = id1;
       item_name_dis = id2;

    }
      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        cb_material = new CustomResource.ComboBoxSuggestion();
        cb_discipline = new CustomResource.ComboBoxSuggestion();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_material1 = new CustomResource.ComboBoxSuggestion();
        cb_discipline1 = new CustomResource.ComboBoxSuggestion();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        dateChooser1.setDateFormat("yyyy-MM-dd");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_material.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Material" }));
        cb_material.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_material.setName(""); // NOI18N
        cb_material.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cb_materialPopupMenuWillBecomeVisible(evt);
            }
        });
        cb_material.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_materialActionPerformed(evt);
            }
        });
        jPanel1.add(cb_material, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 272, -1));

        cb_discipline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID #1", "MT", "VD", "EQ", "TR", "TO", "CO", "OE", "OS", "OC", "AI", "QI", "SC", "CS", "OI" }));
        cb_discipline.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_discipline.setName(""); // NOI18N
        cb_discipline.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cb_disciplinePopupMenuWillBecomeVisible(evt);
            }
        });
        cb_discipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_disciplineActionPerformed(evt);
            }
        });
        jPanel1.add(cb_discipline, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 272, -1));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Spec", "Name Spec", "Stok"
            }
        ));
        jScrollPane1.setViewportView(jTable3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 515, 164));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 610, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 51, 51));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("List");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 530, 20));

        jLabel5.setBackground(new java.awt.Color(0, 51, 51));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Supllier Category");
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 530, 20));

        cb_material1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Material" }));
        cb_material1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_material1.setName(""); // NOI18N
        cb_material1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cb_material1PopupMenuWillBecomeVisible(evt);
            }
        });
        cb_material1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_material1ActionPerformed(evt);
            }
        });
        jPanel1.add(cb_material1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 272, -1));

        cb_discipline1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID #1", "MT", "VD", "EQ", "TR", "TO", "CO", "OE", "OS", "OC", "AI", "QI", "SC", "CS", "OI" }));
        cb_discipline1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cb_discipline1.setName(""); // NOI18N
        cb_discipline1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cb_discipline1PopupMenuWillBecomeVisible(evt);
            }
        });
        cb_discipline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_discipline1ActionPerformed(evt);
            }
        });
        jPanel1.add(cb_discipline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 272, -1));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Spec", "Name Spec", "Stok"
            }
        ));
        jScrollPane2.setViewportView(jTable4);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 515, 164));

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_materialPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_materialPopupMenuWillBecomeVisible
               // TODO add your handling code here:
    }//GEN-LAST:event_cb_materialPopupMenuWillBecomeVisible

    private void cb_materialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_materialActionPerformed
if (cb_material.getSelectedItem() == null) {

        } else {
            combobox_material();

            tampil_comboboxdiscipline();
            
        }     // TODO add your handling code here:
    }//GEN-LAST:event_cb_materialActionPerformed

    private void cb_disciplinePopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_disciplinePopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_disciplinePopupMenuWillBecomeVisible

    private void cb_disciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_disciplineActionPerformed
if (cb_discipline.getSelectedItem() == null) {

        } else {
          combobox_spek();
tampil_table_spek();
            
        } 
       // TODO add your handling code here:
    }//GEN-LAST:event_cb_disciplineActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String id;
String id1;
DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();
int row = jTable3.getSelectedRow();
id = item +"-"+spec1+"-"+model1.getValueAt(row, 0);
id1 = item_name +"-"+item_name_dis+"-"+model1.getValueAt(row, 1);



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_material1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_material1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_material1PopupMenuWillBecomeVisible

    private void cb_material1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_material1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_material1ActionPerformed

    private void cb_discipline1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cb_discipline1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_discipline1PopupMenuWillBecomeVisible

    private void cb_discipline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_discipline1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_discipline1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier_disc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier_disc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier_disc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier_disc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier_disc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomResource.ComboBoxSuggestion cb_discipline;
    private CustomResource.ComboBoxSuggestion cb_discipline1;
    private CustomResource.ComboBoxSuggestion cb_material;
    private CustomResource.ComboBoxSuggestion cb_material1;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
