/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HumanResource;

import Main.MasterForm;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import CustomResource.CandidateSession;
import CustomResource.koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author hi
 */
public class CandidateProfile extends MasterForm {

    private static final int TA_ROWS = 5;
    private static final int TA_COLS = 20;
    Statement stm;
    ResultSet rs;
    Connection koneksi;
    JasperReport jasperreport;
    JasperDesign jasperdesign;
    JasperPrint jasperprint;
    Map<String, Object> param = new HashMap<String, Object>();

    public CandidateProfile() {
        initComponents();
        MyWindow();
        openDB();
        jScrollPane3.getVerticalScrollBar().setUnitIncrement(16);

        getDataCandidate();

        ((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(JLabel.CENTER);

        ((DefaultTableCellRenderer) jTable2.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(JLabel.CENTER);

        ((DefaultTableCellRenderer) jTable3.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(JLabel.CENTER);
    }
    
    private void openDB() {
        try {
            koneksi kon = new koneksi();
            koneksi = kon.getConnection();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "maaf, Tidak terhubung database");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelSallary = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelBPJSkerja = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelJob = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel90 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        labelKTP = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelTTL = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelMarital = new javax.swing.JLabel();
        labelMail = new javax.swing.JLabel();
        labelMobile = new javax.swing.JLabel();
        labelNPWP = new javax.swing.JLabel();
        labelBPJS = new javax.swing.JLabel();
        labelfoto = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("BPJS Ketenaga Kerjaan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 120, 20));

        labelSallary.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelSallary.setText("SALARRY");
        jPanel1.add(labelSallary, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 50, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("NAMA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 40, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("NO HP");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 40, 20));

        labelBPJSkerja.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelBPJSkerja.setText("NO KTP");
        jPanel1.add(labelBPJSkerja, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 300, 170, 20));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("STATUS PERNIKAHAN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 120, 20));

        labelJob.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelJob.setText("JOB APPLYING");
        jPanel1.add(labelJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 90, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel9.setText("TEMPAT, TANGGAL LAHIR");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 140, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel10.setText("JENIS KELAMIN");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 90, 20));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setText(":");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 20, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel12.setText("NPWP");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 40, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 230, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel13.setText("Alamat Rumah / Home Address");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 210, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel14.setText("Tempat Tinggal saat ini / Current Address");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Riwayat Pendidikan / Academic");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 640, 20));

        jTable2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal Lulus", "Nama Sekolah/Universitas", "Lokasi", "Jurusan/Bidang Keahlian"
            }
        ));
        jTable2.setCellSelectionEnabled(true);
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setShowHorizontalLines(true);
        jTable2.setShowVerticalLines(true);
        jTable2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTable2InputMethodTextChanged(evt);
            }
        });
        jScrollPane20.setViewportView(jTable2);

        jPanel1.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 820, 80));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Status Keluarga / Family");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, -1, 30));

        jSeparator2.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 630, 680, 20));

        jTable3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Anggota", "Hubungan", "Tanggal Lahir", "Tinggal Bersama  (Ya atau Tidak)", "No Handphone"
            }
        ));
        jTable3.setShowHorizontalLines(true);
        jTable3.setShowVerticalLines(true);
        jScrollPane21.setViewportView(jTable3);

        jPanel1.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 820, 80));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Sertifikat Keahlian / Certificate Skill");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 750, -1, 30));

        jSeparator3.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 770, 620, 20));

        jTable1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Diraih pada Tanggal", "Nama Sertifikat", "Nama Badan Penyelenggara", "Lokasi Penyelenggara", "No. Sertifikat"
            }
        ));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane4.setViewportView(jTable1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 790, 820, 80));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Pengenalan Diri Untuk Bergabung");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1120, -1, 30));

        jSeparator4.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 1140, 620, 20));

        jLabel90.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel90.setText("1. Motivasi untuk Melamar");
        jPanel1.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1150, 350, 30));

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextArea3.setRows(5);
        jScrollPane23.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1180, 800, 130));

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTextArea4.setRows(5);
        jScrollPane24.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1350, 800, 130));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("SKCK");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 1270, -1, 30));

        jSeparator5.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1510, 760, 20));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Terima Lamaran");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 1600, 170, 40));

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Tolak Lamaran");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1600, 170, 40));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 255));
        jLabel15.setText("Data Diri Calon Karyawan / Employee Personal Information");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 520, 40));

        jLabel93.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel93.setText("2. Lainnya (Kepribadian/Latar Belakang Keluarga)");
        jPanel1.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1320, 350, 30));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel21.setText("JOB APPLYING :");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 90, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("SALARRY :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 60, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("BPJS Kesehatan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 90, 20));

        jLabel22.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel22.setText("EMAIL");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 40, 20));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel23.setText(":");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 20, 20));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel24.setText(":");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 270, 20, 20));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel25.setText(":");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 20, 20));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel26.setText(":");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 20, 20));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel27.setText(":");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 20, 20));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel28.setText(":");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 20, 20));

        jLabel29.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel29.setText(":");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 20, 20));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel30.setText(":");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 20, 20));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel31.setText(":");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 20, 20));

        jLabel32.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel32.setText("NO KTP");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 40, 20));

        labelKTP.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelKTP.setText("NO KTP");
        jPanel1.add(labelKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 170, 20));

        labelNama.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelNama.setText("NO KTP");
        jPanel1.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 170, 20));

        labelTTL.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelTTL.setText("NO KTP");
        jPanel1.add(labelTTL, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 170, 20));

        labelGender.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelGender.setText("NO KTP");
        jPanel1.add(labelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 170, 20));

        labelMarital.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelMarital.setText("NO KTP");
        jPanel1.add(labelMarital, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 170, 20));

        labelMail.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelMail.setText("NO KTP");
        jPanel1.add(labelMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 170, 20));

        labelMobile.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelMobile.setText("NO KTP");
        jPanel1.add(labelMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 170, 20));

        labelNPWP.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelNPWP.setText("NO KTP");
        jPanel1.add(labelNPWP, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, 170, 20));

        labelBPJS.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        labelBPJS.setText("NO KTP");
        jPanel1.add(labelBPJS, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 170, 20));

        labelfoto.setBackground(new java.awt.Color(255, 255, 204));
        labelfoto.setOpaque(true);
        jPanel1.add(labelfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 130, 140));

        jButton3.setText("Print/Save Resume");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 1530, -1, 40));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Perusahaan/Company Name", "Jabatan/Job Position", "Periode/Period", "Karir/career"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable4);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 960, 820, 120));

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setText("Riwayat Pekerjaan/Summary Career");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 900, -1, 30));

        jSeparator6.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 920, 610, 20));

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1169, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable2InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2InputMethodTextChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            koneksi.createStatement().executeUpdate("UPDATE cd_employee SET `approval` = '1' WHERE id_employee = '"+CandidateSession.getCandidateID()+"'");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lamaran gagal Diteruskan");
        }
        Main.main.getMain().showForm(new CandidateList());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            koneksi.createStatement().executeUpdate("UPDATE cd_employee SET `approval` = '10' WHERE id_employee = '"+CandidateSession.getCandidateID()+"'");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Lamaran gagal Diteruskan");
        }
        Main.main.getMain().showForm(new CandidateList());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Connection kon =DriverManager.getConnection("jdbc:mysql://localhost/achivonapp","root","");
            param.clear();
            param.put("id",CandidateSession.getCandidateID());
            String reportPath = "C:\\Program Files (x86)\\AchivonAPP\\cdemployee.jasper";
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportPath, param, kon);
            JasperViewer viewer = new JasperViewer(jasperPrint, false);
            viewer.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JLabel labelBPJS;
    private javax.swing.JLabel labelBPJSkerja;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelJob;
    private javax.swing.JLabel labelKTP;
    private javax.swing.JLabel labelMail;
    private javax.swing.JLabel labelMarital;
    private javax.swing.JLabel labelMobile;
    private javax.swing.JLabel labelNPWP;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelSallary;
    private javax.swing.JLabel labelTTL;
    public static javax.swing.JLabel labelfoto;
    // End of variables declaration//GEN-END:variables
    private void MyWindow() {
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screen.width, screen.height - 45);
        this.setPreferredSize(new Dimension(screen.width, screen.height - 100));
    }
    
    private void getDataCandidate(){
        try {
            ResultSet myRess = koneksi.createStatement().executeQuery("SELECT * FROM cd_employee WHERE id_employee = '"+CandidateSession.getCandidateID()+"'");
            while (myRess.next()) {
                labelNama.setText(myRess.getString(2));
                labelKTP.setText(myRess.getString(3));
                labelMail.setText(myRess.getString(4));
                labelNPWP.setText(myRess.getString(5));
                labelGender.setText(myRess.getString(6));
                labelTTL.setText(myRess.getString(7) + ", " + myRess.getString(8));
                labelMarital.setText(myRess.getString(9));
                labelMobile.setText(myRess.getString(10));
                labelBPJS.setText(myRess.getString(11));
                labelBPJSkerja.setText(myRess.getString(11));
                labelJob.setText(myRess.getString(12));
                labelSallary.setText(myRess.getString(13));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Maaf, Data Tidak Dapat kami temukan");
        }
        DefaultTableModel MyModel2 = (DefaultTableModel) jTable2.getModel();
        int row2 = jTable2.getRowCount();
        for (int i = 0; i < row2; i++) {
            MyModel2.removeRow(0);
        }
        try {
            ResultSet myRess = koneksi.createStatement().executeQuery("SELECT * FROM cd_academic WHERE id_employee = '"+CandidateSession.getCandidateID()+"'");
            while (myRess.next()) {
                String myData[] = {myRess.getString(3), myRess.getString(4), myRess.getString(5), myRess.getString(6)};
                MyModel2.addRow(myData);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Maaf, Data Akademik Tidak Dapat kami temukan \n Sorry, we cant find academic data");
        }
        DefaultTableModel MyModel3 = (DefaultTableModel) jTable3.getModel();
        int row3 = jTable3.getRowCount();
        for (int i = 0; i < row3; i++) {
            MyModel3.removeRow(0);
        }
        try {
            ResultSet myRess = koneksi.createStatement().executeQuery("SELECT * FROM cd_family WHERE id_employee = '"+CandidateSession.getCandidateID()+"'");
            while (myRess.next()) {
                String myData[] = {myRess.getString(3), myRess.getString(4), myRess.getString(5), myRess.getString(6), myRess.getString(7)};
                MyModel3.addRow(myData);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Maaf, Data Keluarga Tidak Dapat kami temukan \n Sorry, we cant find Family data");
        }
        DefaultTableModel MyModel1 = (DefaultTableModel) jTable1.getModel();
        int row1 = jTable1.getRowCount();
        for (int i = 0; i < row1; i++) {
            MyModel1.removeRow(0);
        }
        try {
            ResultSet myRess = koneksi.createStatement().executeQuery("SELECT * FROM cd_certificates WHERE id_employee = '"+CandidateSession.getCandidateID()+"'");
            while (myRess.next()) {
                String myData[] = {myRess.getString(3), myRess.getString(4), myRess.getString(5), myRess.getString(6), myRess.getString(7)};
                MyModel1.addRow(myData);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Maaf, Data Sertifikat Tidak Dapat kami temukan \n Sorry we cant find Certificate data");
        }
        try {
            ResultSet myRess = koneksi.createStatement().executeQuery("SELECT * FROM cd_adress WHERE id_employee = '"+CandidateSession.getCandidateID()+"'");
            while (myRess.next()) {
                jTextArea1.setText(myRess.getString(8) + ", \n" + myRess.getString(7) + ", " + myRess.getString(6) + ", \n" + myRess.getString(5) + ", " + myRess.getString(4) + ", \n" + myRess.getString(3));
                jTextArea2.setText(myRess.getString(14) + ", \n" + myRess.getString(13) + ", " + myRess.getString(12) + ", \n" + myRess.getString(11) + ", " + myRess.getString(10) + ", \n" + myRess.getString(9));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Maaf, Data Alamat Tidak Dapat kami temukan \n Sorry we cant find Address data");
        }
        try {
            ResultSet myRess = koneksi.createStatement().executeQuery("SELECT * FROM cd_motivation WHERE id_employee = '"+CandidateSession.getCandidateID()+"'");
            while (myRess.next()) {
                jTextArea3.setText(myRess.getString(3));
                jTextArea4.setText(myRess.getString(4));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Maaf, Data Motivasi Tidak Dapat kami temukan \n Sorry we cant find Motivation data");
        }
        DefaultTableModel dataModel3 = (DefaultTableModel) jTable4.getModel();
        try {
            stm = koneksi.createStatement();
            rs = stm.executeQuery("select*from cd_summary_career where id_employee = " + CandidateSession.getCandidateID() + "");
            while (rs.next()) {
                String[] data = {
                    rs.getString("company_name"), rs.getString("job_position"), rs.getString("period"), rs.getString("career"),};
                dataModel3.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "data gagal tampil");
        }
    }
    
    @Override
    public void formrefresh() {
    }
}
