package HumanResource;

import Employee.ChangePassword;
import Employee.EmployeeProfilePanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author hi
 */
public class CandidateApplicationFamily extends javax.swing.JPanel {

    CandidateApplication ca;
            CandidateApplicationPersonal candidateApplicationPersonal;
            CandidateApplicationAcademic candidateApplicationAcademic;
            CandidateApplicationFamily candidateApplicationFamily;
            CandidateApplicationCertificates candidateApplicationCertificates;
            CandidateApplicationCareer candidateApplicationCareer;
            CandidateApplicationIntroduction candidateApplicationIntroduction;
            CandidateApplicationSKCK candidateApplicationSKCK;
        CandidateList candidateListPanel;
        CandidateProfile candidateProfile;
    EmployeeConfirmation employeeConfirmation;
    NotificationToNewEmployee notificationToNewEmployee;
    AllocationAnnouncement allocationAnnouncement;
    SummaryStatusCandidatEmployee summaryStatusCandidatEmployee;
    RequestEmployeeAllocation requestEmployeeAllocation;
    LeaveOfAbsense leaveOfAbsense;
    AplicationRehabilitation aplicationRehabilitation;
    ApplicationResignation applicationResignation;
    EmployeeClearanceStatus employeeClearanceStatus;
    ConfirmationHandingOverTakingOver confirmationHandingOverTakingOver;
    DisciplnaryResolution disciplnaryResolution;
    EmployeeEvaluation employeeEvaluation;
    AddJobVacancy addJobVacancy;
    
    EmployeeProfilePanel employeeProfilePanel;
    ChangePassword changePasswordPanel;
    public CandidateApplicationFamily() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane21 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        customTextfield1 = new CustomResource.CustomTextfield();
        customTextfield2 = new CustomResource.CustomTextfield();
        t_tgl = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        radioButtonCustom1 = new CustomResource.RadioButtonCustom();
        radioButtonCustom2 = new CustomResource.RadioButtonCustom();
        jLabel3 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        comboBoxSuggestion1 = new CustomResource.ComboBoxSuggestion();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Anggota / Member Name", "Hubungan / Relation", "Tanggal Lahir / Birthday", "Tinggal Bersama / Cohabit", "No Handphone"
            }
        ));
        jTable3.setShowHorizontalLines(true);
        jTable3.setShowVerticalLines(true);
        jScrollPane21.setViewportView(jTable3);

        add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 820, 90));

        customTextfield1.setLabelText("No Handphone");
        add(customTextfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 260, -1));

        customTextfield2.setLabelText("Nama Anggota / Member Name");
        add(customTextfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 250, -1));
        add(t_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 250, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Tinggal Bersama / Cohabit");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 190, -1));

        radioButtonCustom1.setText("Tidak / No");
        add(radioButtonCustom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        radioButtonCustom2.setText("Ya / Yes");
        add(radioButtonCustom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("Hubungan / Relation");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 190, -1));

        jLabel88.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel88.setText("3. Status Keluarga / Family Status");
        add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 30));

        jSeparator32.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator32.setForeground(new java.awt.Color(255, 0, 0));
        add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 660, 20));
        add(comboBoxSuggestion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 250, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Tanggal Lahir / Birthday");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 190, -1));

        jButton2.setText("Simpan / Save");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, 30));

        jButton3.setText("Lanjut / Next ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, 30));

        jButton4.setText("Ubah / Edit");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, 30));

        jButton5.setText("Hapus / Delete");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, 30));

        jButton6.setText("Kembali / Back");
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
ca.setVisible(false);
                candidateApplicationPersonal.setVisible(true);
                candidateApplicationAcademic.setVisible(false);
                candidateApplicationFamily.setVisible(true);
                candidateApplicationCertificates.setVisible(false);
                candidateApplicationCareer.setVisible(false);
                candidateApplicationIntroduction.setVisible(false);
                candidateApplicationSKCK.setVisible(false);
            candidateListPanel.setVisible(false);
            candidateProfile.setVisible(false);
        employeeConfirmation.setVisible(false);
        notificationToNewEmployee.setVisible(false);
        summaryStatusCandidatEmployee.setVisible(false);
        allocationAnnouncement.setVisible(false);
        requestEmployeeAllocation.setVisible(false);
        leaveOfAbsense.setVisible(false);
        aplicationRehabilitation.setVisible(false);
        applicationResignation.setVisible(false);
        employeeClearanceStatus.setVisible(false);
        confirmationHandingOverTakingOver.setVisible(false);
        disciplnaryResolution.setVisible(false);
        employeeEvaluation.setVisible(false);
        addJobVacancy.setVisible(false);
        
        employeeProfilePanel.setVisible(false);
        changePasswordPanel.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomResource.ComboBoxSuggestion comboBoxSuggestion1;
    private CustomResource.CustomTextfield customTextfield1;
    private CustomResource.CustomTextfield customTextfield2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JTable jTable3;
    private CustomResource.RadioButtonCustom radioButtonCustom1;
    private CustomResource.RadioButtonCustom radioButtonCustom2;
    private com.toedter.calendar.JDateChooser t_tgl;
    // End of variables declaration//GEN-END:variables
}
