/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HumanResource;

import Main.MasterForm;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author hi
 */
public class CandidateApplicationCertificates extends MasterForm {

    /**
     * Creates new form CandidateApplicationFamily
     */
    public CandidateApplicationCertificates() {
        initComponents();
        ((DefaultTableCellRenderer)jTable1.getTableHeader().getDefaultRenderer())
        .setHorizontalAlignment(JLabel.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator31 = new javax.swing.JSeparator();
        jLabel87 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        customTextfield3 = new CustomResource.CustomTextfield();
        customTextfield4 = new CustomResource.CustomTextfield();
        jLabel1 = new javax.swing.JLabel();
        comboBoxSuggestion1 = new CustomResource.ComboBoxSuggestion();
        t_tgl = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        customTextfield5 = new CustomResource.CustomTextfield();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator31.setForeground(new java.awt.Color(255, 0, 0));
        add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 430, 20));

        jLabel87.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel87.setText("4. sertifikat keahlian / Sklill Authorized Certificates");
        add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 300, 30));

        jTable1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "diakuisisi Tanggal / acquisition date", "Nama Sertifikat / Certificate Name", "Nama Badan Penyelenggara / Authority Name", "Lokasi Penyelenggara / Location", "No. Sertifikat"
            }
        ));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 700, 90));

        customTextfield3.setLabelText("Nama Sertifikat / Certificate Namel");
        add(customTextfield3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 270, -1));

        customTextfield4.setLabelText("No. Sertifikat");
        add(customTextfield4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 270, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("diakuisisi Tanggal / acquisition date");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 180, -1));

        comboBoxSuggestion1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        add(comboBoxSuggestion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 270, -1));

        t_tgl.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        add(t_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 220, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Lokasi / Location");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 90, -1));

        customTextfield5.setLabelText("Nama Badan Penyelenggara / Authority Name");
        add(customTextfield5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 270, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("Lanjut / Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, 120, 30));

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Simpan / Save");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 120, 30));

        jButton3.setBackground(new java.awt.Color(255, 204, 51));
        jButton3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ubah / Edit");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 90, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Hapus / Delete");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 120, 30));

        jButton5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton5.setText("Kembali / Back");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 120, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main.main.getMain().showForm(new CandidateApplicationCareer());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomResource.ComboBoxSuggestion comboBoxSuggestion1;
    private CustomResource.CustomTextfield customTextfield3;
    private CustomResource.CustomTextfield customTextfield4;
    private CustomResource.CustomTextfield customTextfield5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser t_tgl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void formrefresh() {
    
    }
}
