/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HumanResource;

import Main.MainPanel;
import Main.MasterForm;

/**
 *
 * @author hi
 */
public class CandidateApplicationIntroduction extends MasterForm{
private static String motivasi;
private static String latar;
    
    public CandidateApplicationIntroduction() {
        initComponents();
    }
    
    public static String motivasi() {
        return motivasi;
    }

    public static String latarbelakang() {
        return latar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel91 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        jLabel90 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        t_motivasi = new javax.swing.JTextArea();
        jLabel94 = new javax.swing.JLabel();
        jScrollPane24 = new javax.swing.JScrollPane();
        t_latarbelakang = new javax.swing.JTextArea();
        jSeparator35 = new javax.swing.JSeparator();
        jLabel93 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        b_done = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel91.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel91.setText("6. Pengenalan diri untuk bergabung degan kami");
        add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 22, 440, 30));

        jSeparator34.setBackground(new java.awt.Color(255, 0, 0));
        jSeparator34.setForeground(new java.awt.Color(255, 0, 0));
        add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 42, 570, 20));

        jLabel90.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel90.setText("1. Motivasi untuk Melamar");
        add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 74, 350, 30));

        t_motivasi.setColumns(20);
        t_motivasi.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        t_motivasi.setRows(5);
        jScrollPane23.setViewportView(t_motivasi);

        add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 110, 768, 130));

        jLabel94.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel94.setText("2. Lainnya (Kepribadian/Latar Belakang Keluarga)");
        add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 258, 350, 30));

        t_latarbelakang.setColumns(20);
        t_latarbelakang.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        t_latarbelakang.setRows(5);
        jScrollPane24.setViewportView(t_latarbelakang);

        add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 294, 771, 130));

        jSeparator35.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 462, 800, 20));

        jLabel93.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel93.setText("7. SKCK");
        add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 442, 50, 30));

        jToggleButton3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jToggleButton3.setText("Kembali / Back");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 620, 120, 40));

        b_done.setBackground(new java.awt.Color(0, 102, 255));
        b_done.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        b_done.setForeground(new java.awt.Color(255, 255, 255));
        b_done.setText("Selesai / Done");
        b_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_doneActionPerformed(evt);
            }
        });
        add(b_done, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
Main.main.getMain().showForm(new CandidateApplicationCareer());        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void b_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_doneActionPerformed
            motivasi = t_motivasi.getText();
            latar = t_latarbelakang.getText();


        Main.main.getMain().showForm(new CandidateApplication());
    }//GEN-LAST:event_b_doneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton b_done;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextArea t_latarbelakang;
    private javax.swing.JTextArea t_motivasi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void formrefresh() {
    
    }
}
