/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaapplication1;

/**
 *
 * @author hi
 */
public class EmployeeProfile extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeProfile
     */
    public EmployeeProfile() {
        initComponents();
        labelJob.setText(MySession.get_JobPosition());
        labelSallary.setText(MySession.get_Sallary());
        labelKTP.setText(MySession.get_ktp());
        labelName.setText(MySession.get_nama());
        labelBirth.setText(MySession.get_birthPlace()+", "+MySession.get_Birthday());
        labelGender.setText(MySession.get_sex());
        labelMarital.setText(MySession.get_marital());
        labelEmail.setText(MySession.get_email());
        labelNumber.setText(MySession.get_mobileNumber());
        labelBPJS.setText(MySession.get_BPJS());
        labelNPWP.setText(MySession.get_NPWP());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFoto = new javax.swing.JLabel();
        labelJob = new javax.swing.JLabel();
        labelKTP = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelBirth = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelMarital = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textHome = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        labelBPJS = new javax.swing.JLabel();
        labelNPWP = new javax.swing.JLabel();
        labelNumber = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelSallary = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textCurrent = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFoto.setText("FOTO");
        add(labelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 130, 140));

        labelJob.setText("JOB APPLYING");
        add(labelJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 220, 30));

        labelKTP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelKTP.setText("NO KTP");
        add(labelKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 270, 20));

        labelName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelName.setText("NAMA");
        add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 270, 20));

        labelBirth.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelBirth.setText("TEMPAT, TANGGAL LAHIR");
        add(labelBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 270, 20));

        labelGender.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelGender.setText("JENIS KELAMIN");
        add(labelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 220, 20));

        labelMarital.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelMarital.setText("STATUS PERNIKAHAN");
        add(labelMarital, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 220, 20));

        jLabel13.setText("Alamat Rumah / Home Address");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        textHome.setColumns(20);
        textHome.setRows(5);
        jScrollPane1.setViewportView(textHome);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 230, -1));

        jLabel14.setText("Tempat Tinggal saat ini / Current Address");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        labelBPJS.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelBPJS.setText("BPJS");
        add(labelBPJS, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 220, 20));

        labelNPWP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelNPWP.setText("NPWP");
        add(labelNPWP, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 220, 20));

        labelNumber.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelNumber.setText("NO HP");
        add(labelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 220, 20));

        labelEmail.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labelEmail.setText("EMAIL");
        add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 220, 20));

        labelSallary.setText("SALARRY");
        add(labelSallary, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 220, 30));

        textCurrent.setColumns(20);
        textCurrent.setRows(5);
        jScrollPane2.setViewportView(textCurrent);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBPJS;
    private javax.swing.JLabel labelBirth;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelJob;
    private javax.swing.JLabel labelKTP;
    private javax.swing.JLabel labelMarital;
    private javax.swing.JLabel labelNPWP;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNumber;
    private javax.swing.JLabel labelSallary;
    private javax.swing.JTextArea textCurrent;
    private javax.swing.JTextArea textHome;
    // End of variables declaration//GEN-END:variables
}
