/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

//import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javaapplication1.MySession;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author hi
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        MyWindow();
        ImageIcon logo = new ImageIcon(getClass().getClassLoader().getResource(".//Pictures//Logo.png"));
        this.setIconImage(logo.getImage());
        openeye.setVisible(false);
        openeye1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        closeeye = new javax.swing.JLabel();
        openeye = new javax.swing.JLabel();
        textPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textPassword1 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        closeeye1 = new javax.swing.JLabel();
        openeye1 = new javax.swing.JLabel();
        textPassword2 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(textUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 240, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 240, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PT.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 50, 20));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 240, 40));

        closeeye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/closedeye.png"))); // NOI18N
        closeeye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeeyeMouseClicked(evt);
            }
        });
        jPanel1.add(closeeye, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 30, 30));

        openeye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/eye.png"))); // NOI18N
        openeye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openeyeMouseClicked(evt);
            }
        });
        jPanel1.add(openeye, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 30, 30));

        textPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPasswordKeyTyped(evt);
            }
        });
        jPanel1.add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 240, 30));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("id Karyawan / Employee id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 170, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Achivon");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 100, 20));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Prestasi Abadi");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 170, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Logo.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 200, 130));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Surat Elektronik / Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 140, 20));

        textPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPassword1KeyTyped(evt);
            }
        });
        jPanel1.add(textPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 240, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Ulang Kata Sandi / Repeat Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 220, 20));

        closeeye1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/closedeye.png"))); // NOI18N
        closeeye1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeeye1MouseClicked(evt);
            }
        });
        jPanel1.add(closeeye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 30, 30));

        openeye1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/eye.png"))); // NOI18N
        openeye1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openeye1MouseClicked(evt);
            }
        });
        jPanel1.add(openeye1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 30, 30));

        textPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPassword2KeyTyped(evt);
            }
        });
        jPanel1.add(textPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 240, 30));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Kata Sandi / Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 140, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/closedeye.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection myConn;
        try {
            myConn = DriverManager.getConnection("jdbc:mysql://localhost/achivonapp", "root", "");
            ResultSet  myRess = myConn.createStatement().executeQuery("SELECT * FROM employee WHERE karyawan_id = '"+textUsername.getText()+"' OR email = '"+textUsername.getText()+"'");
            if(myRess.next()){
                if (textPassword.getText().length()<8) {
                    JOptionPane.showMessageDialog(null, "Pastikan Password Manimal 8 Character");
                }else{
                    if (textPassword.getText().equals(myRess.getString("password"))){
                        JOptionPane.showMessageDialog(null, "Login Berhasil");
                        MySession.set_karyawanID(myRess.getString("karyawan_id"));
                        MySession.set_nama(myRess.getString("name"));
                        MySession.set_ktp(myRess.getString("ktp"));
                        MySession.set_birthPlace(myRess.getString("birth_place"));
                        MySession.set_Birthday(myRess.getString("birthday"));
                        MySession.set_sex(myRess.getString("sex"));
                        MySession.set_marital(myRess.getString("marital"));
                        MySession.set_email(myRess.getString("email"));
                        MySession.set_mobileNumber(myRess.getString("no_hp"));
                        MySession.set_BPJS(myRess.getString("bpjs"));
                        MySession.set_NPWP(myRess.getString("npwp"));
                        MySession.set_JobPosition(myRess.getString("job_position"));
                        MySession.set_Sallary(myRess.getString("sallary"));
                        new main().setVisible(true);
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(rootPane,"Password Salah");
                        textUsername.requestFocus();
                        textPassword.setText("");
                    }
                }
            }else {
                JOptionPane.showMessageDialog(rootPane, "User Tidak Ditemukan");
                textUsername.setText("");
                textPassword.setText("");
                textUsername.requestFocus();
            }
        }catch(SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Mendapatkan Informasi");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPasswordKeyTyped
        if (textPassword.getText().length()>7) {
            JOptionPane.showMessageDialog(null, "Password Maximal 8 Character");
            evt.consume();
        }
    }//GEN-LAST:event_textPasswordKeyTyped

    private void textPassword1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPassword1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textPassword1KeyTyped

    private void textPassword2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPassword2KeyTyped
        if (textPassword2.getText().length()>7) {
            JOptionPane.showMessageDialog(null, "Password Maximal 8 Character");
            evt.consume();
        }
    }//GEN-LAST:event_textPassword2KeyTyped

    private void openeyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openeyeMouseClicked
        textPassword.setEchoChar('*');
        openeye.setVisible(false);
        closeeye.setVisible(true);
    }//GEN-LAST:event_openeyeMouseClicked

    private void closeeyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeeyeMouseClicked
        textPassword.setEchoChar((char)0);
        openeye.setVisible(true);
        closeeye.setVisible(false);
    }//GEN-LAST:event_closeeyeMouseClicked

    private void closeeye1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeeye1MouseClicked
        textPassword2.setEchoChar((char)0);
        openeye1.setVisible(true);
        closeeye1.setVisible(false);
    }//GEN-LAST:event_closeeye1MouseClicked

    private void openeye1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openeye1MouseClicked
        textPassword2.setEchoChar('*');
        openeye1.setVisible(false);
        closeeye1.setVisible(true);
    }//GEN-LAST:event_openeye1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closeeye;
    private javax.swing.JLabel closeeye1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel openeye;
    private javax.swing.JLabel openeye1;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JPasswordField textPassword1;
    private javax.swing.JPasswordField textPassword2;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables
    private void MyWindow(){
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screen.width/2) - (this.getSize().width/2);
        int y = (screen.height/2) - (this.getSize().height/2);
        this.setLocation(x,y);
    }
}
